name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: npm install
    - name: Test
      run: npm test
    - name: Lint
      run: npm lint
